-- Your SQL goes here

CREATE TABLE THREAD(
   TID    		SERIAL PRIMARY KEY     NOT NULL,
   FIRST_FLOOR	INT	NOT NULL
);

CREATE TABLE POST(
   PID		SERIAL PRIMARY KEY	NOT NULL,
   AUTH		CHAR(16),
   PDATE	   TIMESTAMPTZ 	NOT NULL DEFAULT (now()),
   SUBJECT	CHAR(32),
   COMMENT	Text,
   SID		INT	NOT NULL,
   TID		INT	NOT NULL references THREAD (TID)
);

CREATE TABLE SUBSECTION(
   SID	SERIAL PRIMARY KEY	NOT NULL,
   NAME	CHAR(16) NOT NULL
);

CREATE TABLE ADMIN(
   AID		SERIAL PRIMARY KEY     NOT NULL,
   NAME		CHAR(32)	NOT NULL,
   PASSWORD CHAR(16)	NOT NULL
);